import Head from 'next/head'
import React from 'react'
import Footer from './footer'
import Header from './header'

type Props = {
  title: string
  children?: React.ReactNode
}

const Layout: React.FC<Props> = ({ title, children }) => {
  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="pt-[88px] grow">{children}</main>
      <Footer />
    </div>
  )
}

export default Layout
