import Head from 'next/head'
import React from 'react'
import Footer from './Footer'
import Header from './Header'

type Props = {
  children?: React.ReactNode
}

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <div className="flex flex-col h-screen">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="pt-20 grow">{children}</main>
      <Footer />
    </div>
  )
}

export default Layout
